### ISSUE TITLE
FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)

### ISSUE THREAD

**Issue by lipemorais** [cuducos/my-internet-speed#10]
After run `docker-compose up -d` elm package manager is not able to download the package `"cuducos/elm-format-number": "6.0.0 <= v < 7.0.0"`.

```
➜  my-internet-speed git:(master) docker-compose up -d
Building dashboard
Step 1/5 : FROM node:9.11.1-slim
 ---> 175a853f7bb2
Step 2/5 : WORKDIR /code
 ---> Using cache
 ---> 4ccafc0c8680
Step 3/5 : COPY elm-package.json .
 ---> Using cache
 ---> c033f836e391
Step 4/5 : RUN npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes
 ---> Running in a6cf00605d9a
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.1.0
added 247 packages, removed 41 packages and updated 129 packages in 82.702s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/binwrappers/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/binwrappers/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/binwrappers/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/binwrappers/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.18.0 install /usr/local/lib/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz
+ elm@0.18.0
added 94 packages from 69 contributors in 15.664s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/elm-app-cli.js
/usr/local/bin/create-elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/create-elm-app-cli.js

> elm@0.18.0 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz

> elm-test@0.18.12 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm-test
> node install.js

Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz
Successfully downloaded and processed https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/create-elm-app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/create-elm-app/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/create-elm-app/node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ create-elm-app@1.10.4
added 1302 packages from 733 contributors in 88.077s
Error: The following HTTP request failed.
<https://github.com/cuducos/elm-format-number/zipball/6.0.Starting downloads...

  ✗ debois/elm-dom 1.2.3
  ✗ elm-lang/html 2.0.0
  ✗ cuducos/elm-format-number 6.0.0
  ✗ elm-lang/core 5.1.1
  ✗ elm-lang/svg 2.0.0
  ✗ elm-lang/http 1.0.0
  ✗ elm-lang/virtual-dom 2.0.4
  ✗ eskimoblood/elm-color-extra 5.1.0
  ✗ justinmimbs/elm-date-extra 2.1.1
  ✗ mgold/elm-date-format 1.6.0
  ✗ fredcy/elm-parseint 2.0.0
  ✗ myrho/elm-round 1.0.2
  ✗ terezka/line-charts 1.0.0
0/>

FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)

ERROR: Service 'dashboard' failed to build: The command '/bin/sh -c npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes' returned a non-zero code: 1
```

**Comment by cuducos** [comment]
> `FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)`

It looks like a temporary GitHub failure. I just ran it here and it succeeded. Can you test it again?


<details>

```
$ docker-compose build --no-cache dashboard                                                                                       
Building dashboard
Step 1/5 : FROM node:9.11.1-slim
 ---> fa35876db29d
Step 2/5 : WORKDIR /code
Removing intermediate container 30a01c466727
 ---> f17a3373e9a3
Step 3/5 : COPY elm-package.json .
 ---> a92979beae0d
Step 4/5 : RUN npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes
 ---> Running in 64f934544211
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.1.0
added 247 packages, removed 41 packages and updated 129 packages in 20.146s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/binwrappers/elm-make
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/binwrappers/elm
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/binwrappers/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/binwrappers/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.18.0 install /usr/local/lib/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz
+ elm@0.18.0
added 94 packages from 69 contributors in 14.943s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/elm-app-cli.js
/usr/local/bin/create-elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/create-elm-app-cli.js

> elm@0.18.0 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz

> elm-test@0.18.12 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm-test
> node install.js

Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz
Successfully downloaded and processed https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/create-elm-app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/create-elm-app/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/create-elm-app/node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ create-elm-app@1.10.4
added 1302 packages from 733 contributors in 83.569s
Starting downloads...

  ● debois/elm-dom 1.2.3
  ● elm-lang/html 2.0.0
  ● cuducos/elm-format-number 6.0.0
  ● elm-lang/core 5.1.1
  ● elm-lang/http 1.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/svg 2.0.0
  ● eskimoblood/elm-color-extra 5.1.0
  ● fredcy/elm-parseint 2.0.0
  ● mgold/elm-date-format 1.6.0
  ● myrho/elm-round 1.0.2
  ● justinmimbs/elm-date-extra 2.1.1
  ● terezka/line-charts 1.0.0

Packages configured successfully!
Removing intermediate container 64f934544211
 ---> 299e81840f0b
Step 5/5 : CMD ["elm-app", "start"]
 ---> Running in c1e11ca28a9b
Removing intermediate container c1e11ca28a9b
 ---> 74d9167a6334
Successfully built 74d9167a6334
Successfully tagged my-internet-speed_dashboard:latest
```

</details>

**Comment by lipemorais** [comment]
I have tried in different moments but the issue is consistent.

Looking for this error I found a similar [issue](https://github.com/bos/wreq/issues/5#issuecomment-108086543) that says about a file `/etc/protocols` based on this issue I added the line `RUN echo "tcp	6	TCP		# transmission control protocol" > /etc/protocols` to `dashboard/Dockerfile` and it worked perfectly.

What comes to my mind is do a PR with this change but I'm wondering why does it do not work for me and works for you. 🤔 

```
  my-internet-speed git:(master) ✗ docker-compose up --build -d
Building dashboard
Step 1/6 : FROM node:9.11.1-slim
 ---> 175a853f7bb2
Step 2/6 : WORKDIR /code
 ---> Using cache
 ---> 4ccafc0c8680
Step 3/6 : COPY elm-package.json .
 ---> Using cache
 ---> c033f836e391
Step 4/6 : RUN echo "tcp	6	TCP		# transmission control protocol" > /etc/protocols
 ---> Running in 8a5a83ae58d6
Removing intermediate container 8a5a83ae58d6
 ---> b4395e0de723
Step 5/6 : RUN npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes
 ---> Running in 757e5433b848
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.1.0
added 247 packages, removed 41 packages and updated 129 packages in 30.53s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/binwrappers/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/binwrappers/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/binwrappers/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/binwrappers/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.18.0 install /usr/local/lib/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz
+ elm@0.18.0
added 94 packages from 69 contributors in 55.401s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/elm-app-cli.js
/usr/local/bin/create-elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/create-elm-app-cli.js

> elm@0.18.0 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz

> elm-test@0.18.12 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm-test
> node install.js

Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz
Successfully downloaded and processed https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/create-elm-app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/create-elm-app/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/create-elm-app/node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ create-elm-app@1.10.4
added 1302 packages from 733 contributors in 94.851s
Starting downloads...

  ● debois/elm-dom 1.2.3
  ● cuducos/elm-format-number 6.0.0
  ● elm-lang/html 2.0.0
  ● elm-lang/core 5.1.1
  ● elm-lang/http 1.0.0
  ● elm-lang/svg 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● eskimoblood/elm-color-extra 5.1.0
  ● fredcy/elm-parseint 2.0.0
  ● justinmimbs/elm-date-extra 2.1.1
  ● mgold/elm-date-format 1.6.0
  ● myrho/elm-round 1.0.2
  ● terezka/line-charts 1.0.0

Packages configured successfully!
Removing intermediate container 757e5433b848
 ---> f6c37d717b22
Step 6/6 : CMD ["elm-app", "start"]
 ---> Running in f804f74ca313
Removing intermediate container f804f74ca313
 ---> 2ee997c119dc
Successfully built 2ee997c119dc
Successfully tagged my-internet-speed_dashboard:latest
Building flower
Step 1/7 : FROM python:3.6.5-slim
 ---> 0acac5f4cdb6
Step 2/7 : WORKDIR /code
 ---> Using cache
 ---> 60cb81de4912
Step 3/7 : ADD Pipfile Pipfile
 ---> Using cache
 ---> 9129dbe7555d
Step 4/7 : ADD Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> faceef196b86
Step 5/7 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&     apt-get update &&     apt-get -qq -y install apt-transport-https &&     apt-get -qq -y install gcc libpq-dev python3-dev &&     pip install -U black pip pipenv &&     pipenv install --dev --deploy --system &&     apt-get -qq -y remove apt-transport-https gcc python3-dev &&     apt-get -qq -y autoremove &&     apt-get autoclean &&     rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
 ---> Using cache
 ---> dace126604e3
Step 6/7 : ADD my_internet_speed/ my_internet_speed/
 ---> Using cache
 ---> 81f358a15a8e
Step 7/7 : CMD ["celery", "-A", "my_internet_speed", "worker", "-B"]
 ---> Using cache
 ---> aabdf6f1a8da
Successfully built aabdf6f1a8da
Successfully tagged my-internet-speed_flower:latest
Building beat
Step 1/7 : FROM python:3.6.5-slim
 ---> 0acac5f4cdb6
Step 2/7 : WORKDIR /code
 ---> Using cache
 ---> 60cb81de4912
Step 3/7 : ADD Pipfile Pipfile
 ---> Using cache
 ---> 9129dbe7555d
Step 4/7 : ADD Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> faceef196b86
Step 5/7 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&     apt-get update &&     apt-get -qq -y install apt-transport-https &&     apt-get -qq -y install gcc libpq-dev python3-dev &&     pip install -U black pip pipenv &&     pipenv install --dev --deploy --system &&     apt-get -qq -y remove apt-transport-https gcc python3-dev &&     apt-get -qq -y autoremove &&     apt-get autoclean &&     rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
 ---> Using cache
 ---> dace126604e3
Step 6/7 : ADD my_internet_speed/ my_internet_speed/
 ---> Using cache
 ---> 81f358a15a8e
Step 7/7 : CMD ["celery", "-A", "my_internet_speed", "worker", "-B"]
 ---> Using cache
 ---> aabdf6f1a8da
Successfully built aabdf6f1a8da
Successfully tagged my-internet-speed_beat:latest
my-internet-speed_db_1 is up-to-date
my-internet-speed_api_1 is up-to-date
my-internet-speed_broker_1 is up-to-date
Recreating my-internet-speed_dashboard_1 ...
Recreating my-internet-speed_dashboard_1 ... error

ERROR: for my-internet-speed_dashboard_1  no such image: sha256:3e8d905c9ca046f3904176a0e3f522dfcf07dd3e8272d732e7e9ed16050bb76f: No such image: sha256:3e8d905c9ca046f3904176a0e3f522dfcf07dd3e8272d732e7e9ed16050bb76f

ERROR: for dashboard  no such image: sha256:3e8d905c9ca046f3904176a0e3f522dfcf07dd3e8272d732e7e9ed16050bb76f: No such image: sha256:3e8d905c9ca046f3904176a0e3f522dfcf07dd3e8272d732e7e9ed16050bb76f
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Building dashboard
Step 1/6 : FROM node:9.11.1-slim
 ---> 175a853f7bb2
Step 2/6 : WORKDIR /code
 ---> Using cache
 ---> 4ccafc0c8680
Step 3/6 : COPY elm-package.json .
 ---> Using cache
 ---> c033f836e391
Step 4/6 : RUN echo "tcp	6	TCP		# transmission control protocol" > /etc/protocols
 ---> Using cache
 ---> b4395e0de723
Step 5/6 : RUN npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes
 ---> Using cache
 ---> f6c37d717b22
Step 6/6 : CMD ["elm-app", "start"]
 ---> Using cache
 ---> 2ee997c119dc
Successfully built 2ee997c119dc
Successfully tagged my-internet-speed_dashboard:latest
Building flower
Step 1/7 : FROM python:3.6.5-slim
 ---> 0acac5f4cdb6
Step 2/7 : WORKDIR /code
 ---> Using cache
 ---> 60cb81de4912
Step 3/7 : ADD Pipfile Pipfile
 ---> Using cache
 ---> 9129dbe7555d
Step 4/7 : ADD Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> faceef196b86
Step 5/7 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&     apt-get update &&     apt-get -qq -y install apt-transport-https &&     apt-get -qq -y install gcc libpq-dev python3-dev &&     pip install -U black pip pipenv &&     pipenv install --dev --deploy --system &&     apt-get -qq -y remove apt-transport-https gcc python3-dev &&     apt-get -qq -y autoremove &&     apt-get autoclean &&     rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
 ---> Using cache
 ---> dace126604e3
Step 6/7 : ADD my_internet_speed/ my_internet_speed/
 ---> Using cache
 ---> 81f358a15a8e
Step 7/7 : CMD ["celery", "-A", "my_internet_speed", "worker", "-B"]
 ---> Using cache
 ---> aabdf6f1a8da
Successfully built aabdf6f1a8da
Successfully tagged my-internet-speed_flower:latest
Building beat
Step 1/7 : FROM python:3.6.5-slim
 ---> 0acac5f4cdb6
Step 2/7 : WORKDIR /code
 ---> Using cache
 ---> 60cb81de4912
Step 3/7 : ADD Pipfile Pipfile
 ---> Using cache
 ---> 9129dbe7555d
Step 4/7 : ADD Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> faceef196b86
Step 5/7 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&     apt-get update &&     apt-get -qq -y install apt-transport-https &&     apt-get -qq -y install gcc libpq-dev python3-dev &&     pip install -U black pip pipenv &&     pipenv install --dev --deploy --system &&     apt-get -qq -y remove apt-transport-https gcc python3-dev &&     apt-get -qq -y autoremove &&     apt-get autoclean &&     rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
 ---> Using cache
 ---> dace126604e3
Step 6/7 : ADD my_internet_speed/ my_internet_speed/
 ---> Using cache
 ---> 81f358a15a8e
Step 7/7 : CMD ["celery", "-A", "my_internet_speed", "worker", "-B"]
 ---> Using cache
 ---> aabdf6f1a8da
Successfully built aabdf6f1a8da
Successfully tagged my-internet-speed_beat:latest
my-internet-speed_db_1 is up-to-date
my-internet-speed_api_1 is up-to-date
my-internet-speed_broker_1 is up-to-date
my-internet-speed_flower_1 is up-to-date
Recreating 3b02d85b7de3_my-internet-speed_dashboard_1 ... done
Recreating my-internet-speed_beat_1                   ... done
```

**Comment by anapaulagomes** [comment]
I got the same error even adding the line suggested by @lipemorais. :cry:  I'm using Ubuntu (16.04).

```
➜  my-internet-speed git:(master) docker --version                                                         
Docker version 18.03.1-ce, build 9ee9f40
➜  my-internet-speed git:(master) docker-compose --version 
docker-compose version 1.21.2, build a133471
```

**Comment by cuducos** [comment]
So bizarre. I cannot reproduce it here neither in macOS nor in Debian. Can you run the command `elm package install cuducos/elm-format-number`? I mean… in a Docker container with Elm such as `codesimple/elm`?

Are you running in x86 or ARM processor? There's a reported Elm incompatibility with ARM (#11).

**Comment by lipemorais** [comment]
@anapaulagomes, can you change your `dashboard/Dockerfile` like the one below? I guess it will fix your problem. I believe that this 2 line will fix it.

```
RUN apt-get update && \
    apt-get install -y netbase
```

_dashboard/Dockerfile_
```
FROM node:9.11.1-slim

WORKDIR /code
COPY elm-package.json .
RUN apt-get update && \
    apt-get install -y netbase
RUN npm install -g npm@latest && \
    npm install -g --unsafe-perm elm@0.18.0 && \
    npm install -g --unsafe-perm create-elm-app@1.10.4 && \
    elm package install --yes

CMD ["elm-app", "start"]
```

**Comment by cuducos** [comment]
If so, fell free to open a PR – otherwise next time I code for this project I'll do it ; ) I'd just recommend merging the two `RUN` commands and cleaning up for a smaller image:

```dockerfile
RUN apt-get update && \
    apt-get install -y netbase && \
    npm install -g npm@latest && \
    npm install -g --unsafe-perm elm@0.18.0 && \
    npm install -g --unsafe-perm create-elm-app@1.10.4 && \
    elm package install --yes && \
    apt-get purge -y netbase && \
    rm -rf /var/lib/apt/lists/*
```

([source](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/))

**Comment by anapaulagomes** [comment]
Thank you guys! I am afraid I dont have good news (sorry for the missing acents, Im using german keyboard). When I run the app (the dashboard), I got the same error.

```
Failed to compile

./src/Main.elm

Error: The following HTTP request failed.
<https://github.com/cuducos/elm-format-number/zipball/6.0.0/>

FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)


Starting downloads...

  ✗ elm-lang/html 2.0.0
  ✗ terezka/line-charts 1.0.0
  ✗ fredcy/elm-parseint 2.0.0
  ✗ cuducos/elm-format-number 6.0.0
  ✗ elm-lang/virtual-dom 2.0.4
  ✗ elm-lang/http 1.0.0
  ✗ elm-lang/core 5.1.1
  ✗ mgold/elm-date-format 1.6.0
  ✗ myrho/elm-round 1.0.2
  ✗ eskimoblood/elm-color-extra 5.1.0
  ✗ debois/elm-dom 1.2.3
  ✗ elm-lang/svg 2.0.0
  ✗ justinmimbs/elm-date-extra 2.1.1
```

Looking the logs, I have:

```
Step 4/5 : RUN apt-get update &&     apt-get install -y netbase &&     npm install -g npm@latest &&     npm install -g --unsafe-perm elm@0.18.0 &&     npm install -g --unsafe-perm create-elm-app@1.10.4 &&     elm package install --yes &&     apt-get purge -y netbase &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 795b8b8e664f
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [592 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2420 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 7s (1312 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  ifupdown iproute2 isc-dhcp-client isc-dhcp-common libatm1 libdns-export100
  libirs-export91 libisc-export95 libisccfg-export90 libxtables10
Suggested packages:
  ppp rdnssd net-tools iproute2-doc resolvconf avahi-autoipd
The following NEW packages will be installed:
  ifupdown iproute2 isc-dhcp-client isc-dhcp-common libatm1 libdns-export100
  libirs-export91 libisc-export95 libisccfg-export90 libxtables10 netbase
0 upgraded, 11 newly installed, 0 to remove and 14 not upgraded.
Need to get 1794 kB of archives.
After this operation, 4391 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main libatm1 amd64 1:2.5.1-1.5 [73.3 kB]
Get:2 http://deb.debian.org/debian/ jessie/main libisc-export95 amd64 1:9.9.5.dfsg-9+deb8u15 [141 kB]
Get:3 http://deb.debian.org/debian/ jessie/main libdns-export100 amd64 1:9.9.5.dfsg-9+deb8u15 [457 kB]
Get:4 http://deb.debian.org/debian/ jessie/main libisccfg-export90 amd64 1:9.9.5.dfsg-9+deb8u15 [41.5 kB]
Get:5 http://deb.debian.org/debian/ jessie/main libirs-export91 amd64 1:9.9.5.dfsg-9+deb8u15 [39.2 kB]
Get:6 http://deb.debian.org/debian/ jessie/main iproute2 amd64 3.16.0-2 [426 kB]
Get:7 http://deb.debian.org/debian/ jessie/main ifupdown amd64 0.7.53.1 [67.2 kB]
Get:8 http://deb.debian.org/debian/ jessie/main isc-dhcp-common amd64 4.3.1-6+deb8u3 [211 kB]
Get:9 http://deb.debian.org/debian/ jessie/main isc-dhcp-client amd64 4.3.1-6+deb8u3 [250 kB]
Get:10 http://deb.debian.org/debian/ jessie/main libxtables10 amd64 1.4.21-2+b1 [67.6 kB]
Get:11 http://deb.debian.org/debian/ jessie/main netbase all 5.3 [19.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1794 kB in 2s (808 kB/s)
Selecting previously unselected package libatm1:amd64.
(Reading database ... 8030 files and directories currently installed.)
Preparing to unpack .../libatm1_1%3a2.5.1-1.5_amd64.deb ...
Unpacking libatm1:amd64 (1:2.5.1-1.5) ...
Selecting previously unselected package libisc-export95.
Preparing to unpack .../libisc-export95_1%3a9.9.5.dfsg-9+deb8u15_amd64.deb ...
Unpacking libisc-export95 (1:9.9.5.dfsg-9+deb8u15) ...
Selecting previously unselected package libdns-export100.
Preparing to unpack .../libdns-export100_1%3a9.9.5.dfsg-9+deb8u15_amd64.deb ...
Unpacking libdns-export100 (1:9.9.5.dfsg-9+deb8u15) ...
Selecting previously unselected package libisccfg-export90.
Preparing to unpack .../libisccfg-export90_1%3a9.9.5.dfsg-9+deb8u15_amd64.deb ...
Unpacking libisccfg-export90 (1:9.9.5.dfsg-9+deb8u15) ...
Selecting previously unselected package libirs-export91.
Preparing to unpack .../libirs-export91_1%3a9.9.5.dfsg-9+deb8u15_amd64.deb ...
Unpacking libirs-export91 (1:9.9.5.dfsg-9+deb8u15) ...
Selecting previously unselected package iproute2.
Preparing to unpack .../iproute2_3.16.0-2_amd64.deb ...
Unpacking iproute2 (3.16.0-2) ...
Selecting previously unselected package ifupdown.
Preparing to unpack .../ifupdown_0.7.53.1_amd64.deb ...
Unpacking ifupdown (0.7.53.1) ...
Selecting previously unselected package isc-dhcp-common.
Preparing to unpack .../isc-dhcp-common_4.3.1-6+deb8u3_amd64.deb ...
Unpacking isc-dhcp-common (4.3.1-6+deb8u3) ...
Selecting previously unselected package isc-dhcp-client.
Preparing to unpack .../isc-dhcp-client_4.3.1-6+deb8u3_amd64.deb ...
Unpacking isc-dhcp-client (4.3.1-6+deb8u3) ...
Selecting previously unselected package libxtables10.
Preparing to unpack .../libxtables10_1.4.21-2+b1_amd64.deb ...
Unpacking libxtables10 (1.4.21-2+b1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../archives/netbase_5.3_all.deb ...
Unpacking netbase (5.3) ...
Processing triggers for systemd (215-17+deb8u7) ...
Setting up libatm1:amd64 (1:2.5.1-1.5) ...
Setting up libisc-export95 (1:9.9.5.dfsg-9+deb8u15) ...
Setting up libdns-export100 (1:9.9.5.dfsg-9+deb8u15) ...
Setting up libisccfg-export90 (1:9.9.5.dfsg-9+deb8u15) ...
Setting up libirs-export91 (1:9.9.5.dfsg-9+deb8u15) ...
Setting up iproute2 (3.16.0-2) ...
Setting up ifupdown (0.7.53.1) ...
Creating /etc/network/interfaces.
Setting up isc-dhcp-common (4.3.1-6+deb8u3) ...
Setting up isc-dhcp-client (4.3.1-6+deb8u3) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libxtables10 (1.4.21-2+b1) ...
Setting up netbase (5.3) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.1.0
added 247 packages, removed 41 packages and updated 129 packages in 158.985s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/binwrappers/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/binwrappers/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/binwrappers/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/binwrappers/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.18.0 install /usr/local/lib/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz
+ elm@0.18.0
added 94 packages from 69 contributors in 6.643s
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/elm-app-cli.js
/usr/local/bin/create-elm-app -> /usr/local/lib/node_modules/create-elm-app/bin/create-elm-app-cli.js

> elm@0.18.0 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz

> elm-test@0.18.12 install /usr/local/lib/node_modules/create-elm-app/node_modules/elm-test
> node install.js

Downloading binaries from https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz
Successfully downloaded and processed https://dl.bintray.com/elmlang/elm-test/0.18.12/linux-x64.tar.gz

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/create-elm-app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/create-elm-app/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/create-elm-app/node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ create-elm-app@1.10.4
added 1301 packages from 750 contributors in 41.229s
Starting downloads...

  ● debois/elm-dom 1.2.3
  ● cuducos/elm-format-number 6.0.0
  ● elm-lang/html 2.0.0
  ● elm-lang/core 5.1.1
  ● elm-lang/http 1.0.0
  ● elm-lang/svg 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● fredcy/elm-parseint 2.0.0
  ● mgold/elm-date-format 1.6.0
  ● justinmimbs/elm-date-extra 2.1.1
  ● eskimoblood/elm-color-extra 5.1.0
  ● myrho/elm-round 1.0.2
  ● terezka/line-charts 1.0.0

Packages configured successfully!
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  ifupdown iproute2 isc-dhcp-client isc-dhcp-common libatm1 libdns-export100
  libirs-export91 libisc-export95 libisccfg-export90 libxtables10
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  netbase*
0 upgraded, 0 newly installed, 1 to remove and 14 not upgraded.
After this operation, 67.6 kB disk space will be freed.
(Reading database ... 8221 files and directories currently installed.)
Removing netbase (5.3) ...
Purging configuration files for netbase (5.3) ...
Removing intermediate container 795b8b8e664f
 ---> 3d32aab83414
Step 5/5 : CMD ["elm-app", "start"]
 ---> Running in ac3a0bf1304a
Removing intermediate container ac3a0bf1304a
 ---> 11697d33f8b6
Successfully built 11697d33f8b6
Successfully tagged my-internet-speed_dashboard:latest
WARNING: Image for service dashboard was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling broker (redis:4.0.9)...
```
Im running in x86_64. Any thoughts?

**Comment by lipemorais** [comment]
@anapaulagomes could you share the command that gave this log?

Try to use `docker-compose build --no-cache dashboard && docker-compose up -d`.

In the logs I just can see the success message where before we had an error. 
```
+ create-elm-app@1.10.4
added 1301 packages from 750 contributors in 41.229s
Starting downloads...

  ● debois/elm-dom 1.2.3
  ● cuducos/elm-format-number 6.0.0
  ● elm-lang/html 2.0.0
  ● elm-lang/core 5.1.1
  ● elm-lang/http 1.0.0
  ● elm-lang/svg 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● fredcy/elm-parseint 2.0.0
  ● mgold/elm-date-format 1.6.0
  ● justinmimbs/elm-date-extra 2.1.1
  ● eskimoblood/elm-color-extra 5.1.0
  ● myrho/elm-round 1.0.2
  ● terezka/line-charts 1.0.0

Packages configured successfully!
```

**Comment by anapaulagomes** [comment]
Sorry for not give you guys the right input. The thing that called my attention was the same error just on the dashboard webpage. I only pasted the complete log to give you an idea about it (since I don't know much things on JS/Elm topic hehe). After I rebased the repo, I cleaned my docker containers and images to make sure I was having a fresh start. Then I followed the steps described on README.
And according with Twitter, the app was running. :) Only the dashboard had this issue.

I've ran the command you mentioned @lipemorais but the error remains the same. Should I open a new issue?

**Comment by cuducos** [comment]
> Should I open a new issue?

No need. Let's re-open this one ; )

**Comment by cuducos** [comment]
@anapaulagomes I spotted that on your logs:

```
Image for service dashboard was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
```
I'm not sure if this was before or after your cleaning your Docker images and stuff. And it's not clear what error you see in the browser. Would you mind clarifying that for us? Many thanks (and hope _Fodafone_ gets better over there).

**Comment by anapaulagomes** [comment]
It was after I cleaned it up (I did it twice). Thank you! (_Fodafone_ I couldn't think of better nickname hahaha)

**Comment by cuducos** [comment]
Closed by inactivity (just re-open is we are still on debt on this one)

**Comment by SirFireNewt** [comment]
Thought I would jump in since I just had the same thing happen to me today on ubuntu server 19.04 x86_64

The website reads
```
Failed to compile

./src/Main.elm

Error: The following HTTP request failed.
<https://github.com/cuducos/elm-format-number/zipball/6.0.1/>

FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)


Starting downloads...

  ✗ cuducos/elm-format-number 6.0.1
  ✗ elm-lang/core 5.1.1
  ✗ debois/elm-dom 1.2.3
  ✗ elm-lang/html 2.0.0
  ✗ elm-lang/http 1.0.0
  ✗ myrho/elm-round 1.0.3
  ✗ mgold/elm-date-format 1.8.0
  ✗ elm-lang/svg 2.0.0
  ✗ elm-lang/virtual-dom 2.0.4
  ✗ terezka/line-charts 1.0.0
  ✗ eskimoblood/elm-color-extra 5.1.0
  ✗ fredcy/elm-parseint 2.0.0
  ✗ justinmimbs/elm-date-extra 2.1.1

This error occurred during the build time and cannot be dismissed.
```
I ran `docker-compose build --no-cache dashboard | tee output.txt` 
Build log here https://pastebin.com/CczXaKCm I believe it's basically similar to the logs posted by other people

**Comment by samuelhwilliams** [comment]
I seem to be getting the same thing :( Very sad as this project looks great (and is exactly what I wanted) so would love to be able to get it up and running.

As with @SirFireNewt above, website reads:
```
./src/Main.elm

Error: The following HTTP request failed.
<https://github.com/cuducos/elm-format-number/zipball/6.0.1/>

FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)


Starting downloads...

  ✗ debois/elm-dom 1.2.3
  ✗ elm-lang/http 1.0.0
  ✗ elm-lang/html 2.0.0
  ✗ cuducos/elm-format-number 6.0.1
  ✗ myrho/elm-round 1.0.3
  ✗ elm-lang/svg 2.0.0
  ✗ mgold/elm-date-format 1.8.0
  ✗ elm-lang/core 5.1.1
  ✗ fredcy/elm-parseint 2.0.0
  ✗ justinmimbs/elm-date-extra 2.1.1
  ✗ eskimoblood/elm-color-extra 5.1.0
  ✗ elm-lang/virtual-dom 2.0.4
  ✗ terezka/line-charts 1.0.0
```


Logs from the build process imply these things are already installed...

```
+ create-elm-app@1.10.4
added 1417 packages from 759 contributors in 55.623s
Starting downloads...

  ● debois/elm-dom 1.2.3
  ● elm-lang/core 5.1.1
  ● cuducos/elm-format-number 6.0.1
  ● elm-lang/html 2.0.0
  ● elm-lang/http 1.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/svg 2.0.0
  ● eskimoblood/elm-color-extra 5.1.0
  ● fredcy/elm-parseint 2.0.0
  ● mgold/elm-date-format 1.8.0
  ● justinmimbs/elm-date-extra 2.1.1
  ● myrho/elm-round 1.0.3
  ● terezka/line-charts 1.0.0

Packages configured successfully!
```

**Comment by jordanbertasso** [comment]
Running this on macos x86_64 with docker-compose. I fixed this issue by adding the Dockerfile line to dashboard/dockerfile that lipemorais suggested https://github.com/cuducos/my-internet-speed/issues/10#issuecomment-396458581

**Comment by cuducos** [comment]
Tks for the heads up, @jordanbertasso. Just added the `/etc/protocols` to the main branch then. Still not sure _why_, but anyway hahaha… (I mean, the short answer would be _because it works_, but I still don't get why it worked without it before hand or depending on the use case). Life : )
